spring:
  profiles:
    active:
    - dev
---
server:
  port: 6001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.lai.entities    
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                      

spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            
    driver-class-name: org.gjt.mm.mysql.Driver             
    url: jdbc:mysql://localhost:3306/springcloud         
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                        
      max-wait-millis: 200                               

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance: 
    instance-id: microservicecloud-dept8001x
    prefer-ip-address: true      


---
server:
  port: 7001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.lai.entities   
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                     

spring:
  profiles: pro
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           
    driver-class-name: org.gjt.mm.mysql.Driver            
    url: jdbc:mysql://localhost:3306/springcloud3          
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                         
      max-wait-millis: 200                                  

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance: #\u4FEE\u6539eureka\u663E\u793A\u670D\u52A1\u7684\u4E3B\u673A\u540D
    instance-id: microservicecloud-dept8001x
    prefer-ip-address: true      #访问路径可以显示IP地址

