spring:
  profiles:
    active:
    - dev
---
server:
  port: 6001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lai.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                      # mapper映射文件

spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud          # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance: #\u4FEE\u6539eureka\u663E\u793A\u670D\u52A1\u7684\u4E3B\u673A\u540D
    instance-id: microservicecloud-dept8001x
    prefer-ip-address: true      #访问路径可以显示IP地址

info:
  app.name: lai-microservicecloud
  company.name: com.lai
  build.artifactId: @project.artifactId@
  build.version: @project.version@

---
server:
  port: 7001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lai.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                      # mapper映射文件

spring:
  profiles: pro
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud3          # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance: #\u4FEE\u6539eureka\u663E\u793A\u670D\u52A1\u7684\u4E3B\u673A\u540D
    instance-id: microservicecloud-dept8001x
    prefer-ip-address: true      #访问路径可以显示IP地址

info:
  app.name: lai-microservicecloud
  company.name: com.lai
  build.artifactId: @project.artifactId@
  build.version: @project.version@